spring:
  datasource:
    url: jdbc:mysql://${{MYSQLHOST}}:${{MYSQLPORT}}/${{MYSQL_DATABASE}}
    username: ${{MYSQLUSER}}
    password: ${{MYSQLPASSWORD}}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${{JWT_SECRET}}